const debug = require("@wbe/debug")
const str = "hello debug!"

debug("01-namespace")(str)
debug("02-namespace")(str)
debug("03-namespace")(str)
debug("04-namespace")(str)
debug("05-namespace")(str)
debug("06-namespace")(str)
debug("07-namespace")(str)
debug("08-namespace")(str)
debug("09-namespace")(str)
debug("10-namespace")(str)
debug("11-namespace")(str)
debug("12-namespace")(str)
debug("13-namespace")(str)
debug("14-namespace")(str)
console.log("")
console.log("")
console.log("")
